# Generated by Django 5.0.6 on 2024-06-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_dislike_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='post',
        ),
    ]
