# Generated by Django 5.0.6 on 2024-06-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_dislike_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
