# Generated by Django 5.0.6 on 2024-06-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='create_date',
            new_name='create_at',
        ),
    ]
